cask_args appdir: '/Applications'

# cask 'docker'
cask 'docker-edge'
# brew 'docker'

# cask 'docker-toolbox'

# brew 'docker-completion' # jet와 충돌난다
# brew 'docker-compose-completion'
# brew 'docker-machine-completion'

cask 'jet'
brew 'fleetctl'

# brew 'kubectl'
# brew 'kubernetes-helm'


brew 'kubectx'

brew 'reactiveops/tap/rbac-lookup'
