cask_args appdir: '/Applications'

tap 'homebrew/completions'

# cask 'dockertoolbox'

# brew 'docker-completion' # jet와 충돌난다
brew 'docker-compose-completion'
brew 'docker-machine-completion'

cask 'jet'
brew 'fleetctl'

brew 'kubectl'
