	cask_args appdir: '/Applications'

brew 'vim'

tap 'neovim/neovim'
brew 'neovim'

# cask 'macvim'

# cask 'vimr'

# cask 'atom'

cask 'sublime-text'
# cask 'sublime-text-dev'
cask 'sublime-merge'

cask 'visual-studio-code'

brew 'shellcheck'

# Install uncrustify for Atom Beautify
brew 'uncrustify'

# cask 'oni'

# brew 'micro'
