cask_args appdir: '/Applications'

brew 'tor', args: [ '--with-libnatpmp', '--with-libscrypt', '--with-miniupnpc' ]
brew 'torsocks'
# brew 'arm'
cask 'torbrowser'
#cask 'onionshare'
cask 'tunnelbear'

# brew 'gpg2', args: [ '--with-readline' ]
cask 'gpg-suite'

# cask 'gpg-sync'

cask '1password'
cask '1password-cli'
# cask 'lastpass'
brew 'lastpass-cli', args: [ '--with-doc', '--with-pinentry' ]

tap 'homebrew/fuse'
#brew 'encfs'
#brew 'osxfuse'
#brew 'sshfs'

#cask 'veracrypt'

cask 'keybase'

cask 'authy'

# brew 'dnscrypt-proxy', args: [ '--with-plugins' ]
cask 'dnscrypt'

# brew 'dnsmasq', args: ['--with-dnssec', '--with-libidn']

cask 'adguard'

brew 'openvpn'

cask 'santa'