cask_args appdir: '/Applications'

brew 'tor', args: [ '--with-libnatpmp', '--with-libscrypt', '--with-miniupnpc' ]
brew 'torsocks'
# brew 'arm'
# cask 'tor-browser'
# cask 'onionshare'
# cask 'tunnelbear'

# brew 'gpg2', args: [ '--with-readline' ]
cask 'gpg-suite'

# cask 'gpg-sync'

cask '1password'
cask '1password-cli'
# cask 'lastpass'
brew 'lastpass-cli', args: [ '--with-doc', '--with-pinentry' ]

tap 'ravenac95/sudolikeaboss'
brew 'sudolikeaboss'

# tap 'homebrew/fuse'
# brew 'encfs'
# cask 'osxfuse'
# brew 'sshfs'

# cask 'veracrypt'

cask 'keybase'

# cask 'authy'

# brew 'dnscrypt-proxy', args: [ '--with-plugins' ]
cask 'dnscrypt'

# brew 'dnsmasq', args: ['--with-dnssec', '--with-libidn']

cask 'adguard'

brew 'openvpn'

# cask 'outline-manager'

cask 'santa'
