cask_args appdir: '/Applications'

# See https://github.com/sindresorhus/quick-look-plugins

# Install Markdown Quicklook
# ref: https://github.com/toland/qlmarkdown
# cask 'qlmarkdown'
cask 'qlcommonmark'

# Install other Quicklook plugins
# ref: https://github.com/sindresorhus/quick-look-plugins
cask 'quicklook-csv'

cask 'qlgradle'

cask 'quicklook-json'

cask 'qlcolorcode'

cask 'qlstephen'

cask 'qlprettypatch'

# cask 'betterzip'

cask 'qlimagesize'

cask 'webpquicklook'

cask 'suspicious-package'

cask 'provisionql'

cask 'qlvideo'

# Install QuickLook render plugin for ReST (ReStructuredText) files.
# ref: https://github.com/cluther/qlrest
cask 'qlrest'

cask 'qlmobi'