cask_args appdir: '/Applications'

brew 'git', args: ['--with-blk-sha1', '--with-brewed-curl', '--with-brewed-openssl', '--with-brewed-svn', '--with-gettext', '--with-pcre' '--with-persistent-https']

brew 'git-lfs'
brew 'git-flow'
brew 'git-extras'
brew 'git-standup'
brew 'diff-so-fancy'
brew 'bash-git-prompt'

cask 'sourcetree'
#cask 'gitkraken'

# See https://hackernoon.com/macbook-my-command-line-utilities-f8a121c3b019#.9coythpx9
brew 'tig'
